[package]
name = "whatspp-cloud-api-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Whatsapp Cloud API Rust Client"
homepage = "https://github.com/sajuthankappan/whatsapp-cloud-api-rs"
repository = "https://github.com/sajuthankappan/whatsapp-cloud-api-rs"
readme = "README.md"
keywords = ["whatsapp"]
categories = ["api-bindings"]

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.4", features = ["json"]}
serde = { version = "1.0.127", features = ["derive"]}
serde_json = "1.0.66"


[dev-dependencies]
anyhow = "1.0.43"
dotenv = "0.15.0"
env_logger = "0.9.0"
tokio = { version = "1.10.0", features=["full"]}
